### ISSUE TITLE
Automatic installation only work in Ubuntu 18.04

### ISSUE THREAD

**Issue by zontor** [Libki/libki-server#119]
Hi testing the system in a virtual machine, had some problems using auto installing in debian following the manual.
Manual says it should work with ubuntu server 18.04 LTS, debian 9 (stretch) or debian 10 (buster)
- In debian 10 (tried version 10.0 and 10.1) it fail in some perl catalyst library giving errors to install and not working
- In Debian 9 (tryed version 9.9)  running install.sh says the system is not supported needed to change install.sh because it checks for debian-9 instead of debian-stretch don't know if debian change something in latest release to the name be build different
Then when installing gives a error creating database tables in mariadb (installed auto for debian) of a key too big, trying to import sql directly gives the same error. Think the problem dosn't exist in mysql 5.7 that ubuntu uses.
- In Ubuntu Server 18.04.03 worked fine.

**Comment by loidor** [comment]
Great finds!

I'll look into it and get it sorted as soon as possible.

**Comment by loidor** [comment]
I've taken care of the Deb 9 bugs. Apparently they changed version naming in 9.8 for some reason, and I didn't think stuff through properly when updating the database to utf8mb4, so some indexes were too large for older mysql databases.

I am, however, not able to replicate the Deb 10 bug - I guess that might be the one I corrected this weekend with DBIx::Class::EncodedColumn not installing properly?

Could you test deb 10 again and verify if that's it, or if it's something new? If it's something new I will need a log of your installation.

Instead of `./install.sh`, run `./install.sh 2>&1 | tee install.log` and you should end up with a log file. The easiest way to post it online should be `cat install.log | nc termbin.com 9999`.

**Comment by zontor** [comment]
Sorry for delay, in Debian 10 i've installed first with debian 10.0 and without the corrected DBIx::CLass the i see that debian 10.1 was released and your fix and tried again and was giving some info in libki_server.log
I reinstalled again today, and I think another perl library error now (think not the same as last time) now is DateTime.pm don't remember if was the same last time and Getting this repeated output in log
`Error while loading /home/libki/libki-server/libki.psgi: Can't locate DateTime.pm in @INC (you may need to install the DateTime module) (@INC contains: /home/libki/libki-server/lib /etc/perl /usr/local/lib
/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x
86_64-linux-gnu/perl-base) at /home/libki/libki-server/lib/Libki.pm line 6.
BEGIN failed--compilation aborted at /home/libki/libki-server/lib/Libki.pm line 6.
Compilation failed in require at /home/libki/libki-server/libki.psgi line 4.
BEGIN failed--compilation aborted at /home/libki/libki-server/libki.psgi line 4.
new worker 35009 seems to have failed to start, exit status:512
starting new worker 35010
`
Here is the log of this installation
https://termbin.com/s7yn

**Comment by loidor** [comment]
I read through the specs for 10.1, and none of those updates should affect Libki in any way, meaning that in this case there's really no difference between them.

Onwards. For some reason, the following modules aren't installed properly for you:

- Net::Google::DataAPI::Auth::OAuth2
- DateTime
- DBIx::Class::TimeStamp
- DateTime::Format::DateParse

When I run it on my machines the installer works fine, so that's a bit weird. 

What happens if you manually tries to install those modules?
```
cpanm Net::Google::DataAPI::Auth::OAuth2
cpanm DateTime
cpanm DBIx::Class::TimeStamp
cpanm DateTime::Format::DateParse
```

**Comment by zontor** [comment]
- first one fail in a dependencie that its also a dependencie of DateTime
`Building and testing DateTime-Locale-1.24 ... FAIL`
then do it again and stop on this one
`Building and testing Net-Google-DataAPI-0.2805 ... FAIL`
https://termbin.com/kswc
- second one was installed the second time i tried the Oauth2
- tird an forth was installed manually correctly

I force the installation of Net::Google::DataAPI::Auth::OAuth2 it fail on testing but install but still not working libki_server.log now on loop with this error
`starting new worker 54919
worker 54919 died unexpectedly with status:512, restarting
starting new worker 54938
`

**Comment by loidor** [comment]
I'm sorry, but I can't replicate this. I've tried different machines, Debian 10.0 and 10.1, i386 and x86-64 with as low as 512MB RAM, and it still installs properly. 

From that I conclude that the problem is most likely on your side and not with the installer or Libki itself.

Since Ubuntu worked nicely for you I suggest running it on Ubuntu. 18.04 has been out for so long that I consider it just as stable as Debian stable at this point.
