### ISSUE TITLE
Docker error pam_env(cron:session): Unable to open env file:

### ISSUE THREAD

**Issue by AgnesHPL** [Libki/libki-server#19]
The auth log inside Docker container fills with three repeating messages, of which one is this error:

pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory

This mentions the same symptom and fix: 
https://github.com/tomav/docker-mailserver/issues/401

**Comment by heyitsjoewevers** [comment]
hmm, sounds like the environment inside the container is missing something.
Its probably not anything to worry about. If it was actually something
serious it would have came up as an error ages ago. My guess is that its
looking inside the container for the env file that only exists outside of
the container. But since only 1 task is running on the crontab inside the
container (and its still working!) I wouldn't worry about it.

**Comment by loidor** [comment]
Docker is removed for now. Please use the manual installation.
