### ISSUE TITLE
Move the readme info to the wiki

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#40]
The readme needs modifying and expanding. I'm looking into getting the server to run flawless on Debian 9, Ubuntu 16.04 and 18.04, and from the looks of it, they all need slightly different installation instructions. Also, setting up a new Docker installation would need separate installation instructions as well.

The readme is kind of long as it is, and expanding it would make it problematic to navigate through. Putting it into a wiki is the sensible thing to do.

I'm posting this (and a couple of other issues) so I don't forget about them.

**Comment by kylemhall** [comment]
I'm not big on having the readme info on the wiki unless it can be snapshotted. The installation process might very wildly from version to version and if for some reason someone needs to install an old version we don't want to leave them out to dry.

What do you think of using gitbook? Of we used gitbook could just tag the gitbook repo with the same tag each release gets. In addition, we could expand it to become a full manual eventually, rather than just installation instructions.

**Comment by kylemhall** [comment]
I'll start a repo for the 'manual'!

**Comment by kylemhall** [comment]
I've sent an invitation to the Libki GitBook to your gmail account from my bywater solutions account!

**Comment by kylemhall** [comment]
Just so you know I'm waiting for gitbook.io to convert that account to a free for OSS account. Another alternative would be to use https://daux.io/

If you have an opinion on what we should use please let me know!

**Comment by loidor** [comment]
Great! I will have time to look at it tomorrow evening (your daytime, I guess) or on Thursday.

**Comment by kylemhall** [comment]
The gitbook people got back to me and are giving us the free for OSS account so let's stick with Gitbook. It'll be much easier to use in the long run!

**Comment by loidor** [comment]
Great! I have looked a bit at both and prefer Gitbook.

**Comment by loidor** [comment]
I noticed this is done and came out really nice, so I'll close this one.
