### ISSUE TITLE
Server Port 8080 can't handle client requests

### ISSUE THREAD

**Issue by Shadra** [Libki/libki-server#8]
Hi

The client give all needed login information to the server with ipaddress:8080, but there is nothing what response. If I try to open the webseite ipaddress:8080 on the server side I get an error, too. But ipaddress only works for both.

Here is the logfile:
> admin@client1:~$ /usr/local/bin/libkiclient
> OS Username:  "admin"
> Translation file not found: "languages/libkiclient_de_CH"
> QIODevice::read: device not open
> onlyRunFor:  ""
> onlyStopFor:  ""
> LoginWindow::LoginWindow
> LoginWindow::setAllowClose
> LoginWindow::setupActions
> LoginWindow::showMe()
> LoginWindow::resetLoginScreen()
> TimerWindow::TimerWindow
> TimerWindow::setAllowClose
> TimerWindow::setupActions
> TimerWindow::setupTrayIcon()
> NetworkClient::NetworkClient
> LOCATION:  "OG2"
> AGE LIMIT:  ""
> NetworkClient::registerNode
> NetworkClient::processRegisterNodeReply
> Server Result:  ""
> Node Registration FAILED
> LoginWindow::handleReservationStatus
> LoginWindow::attemptLogin
> NetworkClient::attemptLogin
> LOGIN URL:  "http://192.168.1.205:8080/api/client/v1_0?node=Client1&location=OG2&action=login&username=USER&password=PASSWORD"
> NetworkClient::attemptLogin
> NetworkClient::registerNode
> NetworkClient::processAttemptLogoutReply
> Login Failed
> Error Code:  ""
> "LoginWindow::attemptLoginFailure()"
> NetworkClient::processRegisterNodeReply
> Server Result:  ""
> Node Registration FAILED
> LoginWindow::handleReservationStatus
> LoginWindow::attemptLogin
> Password:  "password"
> Hashed Password:  "xx"
> Hash from INI file:  "xx"
> Shutdown password matches, exiting.`

Client: http://192.168.1.205:8080 | did not work
Client: http://192.168.1.205 | works
Server: http://192.168.1.205:8080 | did not work
Server: http://192.168.1.205 | works

In the server manual (https://github.com/Libki/libki-server/blob/master/README.md) I can't find any information what I must configurate, that apache handles port 8080 and gives the requests to the libki server so it can start a session and the node registration would work.

What should I do?

This is the little pice what makes for me unable to rollout libki to all our computers.

**Comment by aprilwhittle** [comment]
I had trouble with the client working with the server too.  My problem was
when I ran the installation exe the first screen would ask for input
specifying the Libki server and I was filling that out wrong.  I found this
worked:

Scheme:
http

Host:
This is the ip of the Libki server

Port:
3000 (I thought this should have been 8080 when I tried)



April Whittle
Chemeketa Community College
Technology Analyst I
april.whittle@chemeketa.edu
phone # 503.584.7407

**Comment by Shadra** [comment]
Oh thank you, you are absolutly correct. The client had port 8080 per default configured, but online with 3000 it works. My bad...
Maybe you know why the countdown on client side does not count towards zero? If I give a client 10 minutes of time, then it shows after 5 minutes still 10 minutes and 100%. But I can use it normaly and it'll correctly recognized by the server.

**Comment by aprilwhittle** [comment]
First thing to ask and check is did you set the cron job at the end of the
directions?  Libki counts by running a cron job every minute that runs a
perl script that does the actual counting in Libki.  The directions have
you do crontab -e as the Libki user.  This is important because a lot of
what was installed and configured was for the Libki user.

If this has been done it could be you need to specify the location or the
complete path that the cron job is to run the perl script form.  I had to
do this, I found an old post actually in the Libki documentation that
commented on this.

This is the script I used as Libki user in crontab -e
* * * * * perl -I /home/libki/perl5/lib/perl5 /home/libki/libki
-server/script/cronjobs/libki.pl
0 0 * * * perl -I /home/libki/perl5/lib/perl5 /home/libki/libki
-server/script/cronjobs/libki_nightly.pl

The very last thing is check the libki.log file.  I had to do this as well,
when the path from the cron job was fixed there was still an error in the
log file saying something to the effect that libki didn't have the right
permissions.  This should be under /home/libki/libki-server or very similar
if you followed the instructions.  At sometime in the installation the
ownership of that file can change to root and it must be libki so Libki can
write to it.

Hope this helps

April Whittle
Chemeketa Community College
Technology Analyst I
april.whittle@chemeketa.edu
phone # 503.584.7407

**Comment by Shadra** [comment]
Thank you!
It works very well :) The logfile was owned by root and the perl jobs had no permission on it.
