### ISSUE TITLE
Table login_sessions grows quite a lot

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#92]
The current "production server" (i.e. the one in use on my library) has been running since Sept -18 now, and I just noticed that the table login_sessions has grown a bit... Right now it contains a bit over 18 million rows.

I just setup a test server where I truncated login_sessions and it seems to run on just fine, but there might be a reason I'm missing? @kylemhall what do you say?

Suggestion: clearing it out with nightly.

**Comment by kylemhall** [comment]
Yeah, the problem is the session manager Catalyst uses doesn't clean up after itself.

The nightly cronjob calls delete_expired_sessions, is this not removing them from the database for you? If not, we should replace it with our own SQL.

https://metacpan.org/pod/Catalyst::Plugin::Session::Store::DBIC#delete_expired_sessions

**Comment by loidor** [comment]
No, apparently it doesn't. Nightly runs all right though, from what I can see. 

I'll output it to a log and check in on it on Monday. Worst case I've missed something in the installer.

**Comment by loidor** [comment]
Apparently I got a work shift today.

Only thing the log complains about is locating object method "days" via "Libki::Model::DB::Setting", which I believe has been taken care of since (again, this install is from Sept -18).

So yeah, I believe we should replace it with a TRUNCATE TABLE (I can't see a reason to storing session data overnight).

**Comment by loidor** [comment]
Taken care of with commit #94.
